#!/bin/env bash
### Error for wrong option handled ###
if [[ "$1" == "--addnodes" ]] || [[ "$1" == "--delnodes" ]] || [[ "$1" == "--configure" ]]; then
  echo "Valid values. So execute the later code"
else
  echo "ERROR: Unknown command line option(s): '$@'"
  exit 10
fi

NODE_ID=$(configcli namespace node id)
FQDN=$(configcli namespace node fqdn)

# TODO: using eval is not secure - need to safely parse variables
eval $(cat /etc/guestconfig/configmeta.json | python -c 'import json,sys;print json.load(sys.stdin)["connections"]["configmaps"]["dsr-config"][0]["data"]["dsr.properties"]')

echo $MAPR_TICKET > $MAPR_TICKETFILE_LOCATION

bash -x ./entrypoint.sh
